### ISSUE TITLE
IMAGO/Authagraph power function setting no longer works on Map Analyzer nor on Map Desginer

### ISSUE THREAD

**Issue by ObmijSelaw** [jkunimune/Map-Projections#10]
Hi Justin! I want to report that the latest update ([The Background Update](https://github.com/jkunimune/Map-Projections/releases/tag/v3.5.1)), has broken the IMAGO/Authagraph Power Function setting. Changing the Power on either the Map Analyzer or the Map Designer Raster when using this particular projection does not seem to do anything. The rest of the settings (Longitude, Latitude, and Centre Meridian) work correctly.

I am running them using a Fedora Linux 39 Workstation container, with Java OpenJDK Runtime Environment (Red_Hat-17.0.9.0.9-2) (build 17.0.9+9), and libraries from openjfx-17.0.9_linux-x64_bin-sdk.

The older 3.4.6 works correctly using the same system and Java installation.
Let me know if there is anything I can do to help you debug this on my end. I appreciate your work!

**Comment by jkunimune** [comment]
Wow, thanks for catching that so quickly!  This is an easy fix.  What happened was I intended to remove the ability to set the power on that projection with the expectation that people would use the "AuthaPower" projection instead if they wanted the parameterization.  But I forgot to remove the actual slider when I removed the slider's functionality.  In retrospect it's probably better to keep this how it was before.  If you install the latest release, the slider should work again.
