### ISSUE TITLE
Invalid SVG output for non-English localisation settings

### ISSUE THREAD

**Issue by fer3852** [jkunimune/Map-Projections#11]
Witnessed behaviour:
- If the Windows (11 22H2) Regional format settings (Settings -> Time & Language -> Language & region) are set to a localisation using the comma as decimal separator (as is the case for many languages other than English), MapDesignerVector outputs invalid svg files since the dots in coordinates are replaced by commas. E.g. the coordinate pair 123.456, 987.654 is transformed into the invalid SVG sequence 123,456, 987,654. See attached file for an example output: ![test](https://github.com/jkunimune/Map-Projections/assets/9251997/97554a7d-6649-483e-a30f-06a92b5a41ba)

Expected behaviour:
- Valid .svg files are output irrespective of the user's localisation settings. In other words, the float(?) to string conversion should be configured to use a dot as the decimal separator in all cases.

Steps to reproduce:
- Set Settings->Time & Language->Language & region->Regional format settings to a language using a comma as decimal separator (tested with _Dutch (Netherlands)_).
- Start MapDesignerVector.exe and save any .svg file.
- Open the resulting .svg file in any .svg viewer, or a text editor to inspect its code.

**Comment by jkunimune** [comment]
Oops, thank you for letting me know.  This should be fixed in the release I published just now.
