### ISSUE TITLE
Is it possible to increase count of gores?

### ISSUE THREAD

**Issue by Chieftl** [jkunimune/Map-Projections#12]
Great product, however when I try to make layout for big globe, it looks like 12 gores  is not enough. Can you explain please, how to increase count of gores for vector maps?

**Comment by jkunimune** [comment]
That's not currently possible, but it shouldn't be a very hard feature to add.  I'll try to do it this weekend and I'll let you know.

**Comment by jkunimune** [comment]
I just pushed [https://github.com/jkunimune/Map-Projections/releases/tag/v3.5.6 v3.5.6], which adds this option in the form of a slider on the gores projection.  You can now have anywhere from 4 to 72 gores.  I can make the maximum higher if you need more but I'm guessing 72 is more than enough.

**Comment by Chieftl** [comment]
Works great, thanks a lot!
