### ISSUE TITLE
Java Linux Noob - I am having trouble running the code.

### ISSUE THREAD

**Issue by csharpee** [jkunimune/Map-Projections#9]
**java version: javac 11.0.18**

I cloned the master repository and installed java-sdk. 

Then in the cloned directory, I ran: 

`javac MapAnalyzer.jar`

and received this error: 

_Class names, 'MapAnalyzer.jar', are only accepted if annotation processing is explicitly requested_

I tested `java MapAnalyzer.jar` and received another error.

_Error: Could not find or load main class MapDesignerRaster.jar_

Also, in the instructions, it says there are: (4 py files) 

```
generate_coastlines.py – Generate an SVG string outlining the continents, islands, and major lakes of the world, to be used as vector input.
generate_graticule.py – Generate an SVG string displaying a map graticule, to be used as vector input.
generate_indicatrices.py – Generate an SVG string outlining an array of Tissot's indiatrices of distortion, to be used as vector input.
generate_orthodromes.py – Generate a mesh of orthodromes in an Equirectangular projection, to be used as vector input.
```

These files do not exist in the most recent release or the master repository.

**Comment by jkunimune** [comment]
Sorry, this should have been covered in the README.  I updated it just now to address this, so it should have the answers to all your questions if you read it now.  To summarize:

The `.jar` files are already compiled, so you don’t call `javac` on them; you call `java -jar`.  But that said, there’s also some additional arguments needed to include JavaFX, so see the new README for more details.

Most of those `.py` files do exist in the newest release, but they’re buried in `src/zupplemental/`.  It’s true that `generate_coastlines.py` no longer exists, and in general I would recommend that if you want to generate SVG strings, you just use `src/zupplemental/compose_maps.py`.

**Comment by csharpee** [comment]
I keep getting:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found

```

The syntax I used on Ubuntu Linux with _javafx-jmods-20_:
```
java --module-path "/home/username/Desktop/Local-Development/Java/javafx-jmods-20/lib" --add-modules "javafx.controls" -jar MapDesignerRaster.jar
```
I found an ol' bug with including multiple modules via command line, but that didn't even work. 
https://bugs.openjdk.org/browse/JDK-8162401

I also tested `'./../javafx-jmods-20/lib'` and `'./../javafx-jmods-20:lib'`, plus tried quotation marks "".

The *:* represents multiple directories though, so it must be something else. Clearly the syntax isn't working.

**Comment by csharpee** [comment]
Awesome, that worked on the first try. I am grateful :raised_hands: 

![image](https://user-images.githubusercontent.com/18726788/231327871-172725ee-0fe7-4912-b1e9-9eb05f2b5115.png)

```
java --module-path './../javafx-sdk-17.0.6/lib' --add-modules javafx.controls,javafx.swing -jar MapDesignerRaster.jar
```
